services:
  db:
    image: mysql
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./db_scripts:/docker-entrypoint-initdb.d
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 5s
            retries: 5

  generator:
    build:
      context: .
      dockerfile: generator_dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
        - 5678:5678

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./db_data